rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ree
gemfile: test/Gemfile
env:
  - MATHN=true
  - MATHN=false
branches:
  only:
    - master
    - stable
notifications:
  irc: {channels: "irc.freenode.org#sass"}
